<?php
const SYSTEMD_STATE_BUSERROR = 'BUSERROR';
const SYSTEMD_STATE_ERRNO = 'ERRNO';
const SYSTEMD_STATE_EXTEND_TIMEOUT_USEC = 'EXTEND_TIMEOUT_USEC';
const SYSTEMD_STATE_FDNAME = 'FDNAME';
const SYSTEMD_STATE_FDSTORE = 'FDSTORE';
const SYSTEMD_STATE_FDSTOREREMOVE = 'FDSTOREREMOVE';
const SYSTEMD_STATE_MAINPID = 'MAINPID';
const SYSTEMD_STATE_READY = 'READY';
const SYSTEMD_STATE_RELOADING = 'RELOADING';
const SYSTEMD_STATE_STATUS = 'STATUS';
const SYSTEMD_STATE_STOPPING = 'STOPPING';
const SYSTEMD_STATE_WATCHDOG = 'WATCHDOG';
const SYSTEMD_STATE_WATCHDOG_USEC = 'WATCHDOG_USEC';

function systemd_notify(bool $unset_environment, string $state, string $value): bool;

function systemd_watchdog_enabled(bool $unset_environment): int;
